SERVER_ADDRESS and BASE_URL to env variables
fd239/go_url_shortener pull request #3
Opened 2022-02-20 13:37 UTC by fd239

2022-02-25 18:22 UTC, fd239 commented
Я немного попутал и не создал отдельную ветку под homework2, прошу простить и проревьюить как есть. В этой ветке исправления по прошлому ревью и все работы по второму спринту

2022-03-02 07:08 UTC, Barugoo commented on internal/app/common/config.go
> +		panic(err)
Давай здесь возвращать ошибку, паника немного для других ситуаций используется
И в том месте, где ты вызываешь эту функцию, если ошибка `!= nil` вызывать `log.Fatal`

2022-03-02 07:09 UTC, Barugoo commented on internal/app/server.go
> +	shortUrl, _ := DB.SaveShortRoute(string(body))
Здесь нужно проверять ошибку

2022-03-02 07:11 UTC, Barugoo commented on internal/app/server_test.go
>  }
`bytes.Buffer` реализует интерфейс `io.Reader`, поэтому здесь ты можешь сделать просто 
```go
return buf
```

2022-03-02 07:43 UTC, Barugoo requested changes
Записал для тебя видео-ревью
https://disk.yandex.ru/i/8Udizy-_17-0Zw

2022-03-04 09:15 UTC, fd239 commented
Поправил по ревью, но не понял о чем речь "Поправь еще go vet test"?

2022-03-04 20:53 UTC, Barugoo approved these changes
Хорошо!

2022-03-05 16:42 UTC, merged

2022-03-10 20:15 UTC, Barugoo commented on internal/app/common/tests.go
> +	TestDBName  = "TEST_DB.txt"
Мб тогда в файлы с тестами их и унести?

2022-03-10 20:16 UTC, Barugoo commented on internal/app/handlers/handlers.go
> +		http.Error(w, err.Error(), http.StatusBadRequest)
Лучше писать какое-нибудь generic-пояснение клиенту в ответе, иначе если писать текст ошибок напрямую - раскроем реализацию, чего лучше не делать
Я бы реальную ошибку залоггировал, а пользователю просто вернул `unable to parse body` или типа того:
```go
log.Printf("io.ReadAll: %v\n", err) // обрати внимание на знак переноса в конце форматирующей строки
http.Error(w, "unable to read body", http.StatusInternalServerError)
return

2022-03-10 20:18 UTC, Barugoo commented on internal/app/handlers/handlers.go
> +	json.NewEncoder(w).Encode(response)
Здесь надо проверять ошибку, понимаю, что в случае разрыва коннекта она роли не играет, но ошибка сериализации может быть не только по этой причине

2022-03-10 20:21 UTC, Barugoo reviewed
Отлично!