Homework5
fd239/go_url_shortener pull request #6
Opened 2022-05-31 20:35 UTC by fd239

2022-06-05 22:47 UTC, Barugoo commented on cmd/shortener/main.go
> +	_ "net/http/pprof" // подключаем пакет pprof
Давай тогда уж коммент на англицком

2022-06-05 22:48 UTC, Barugoo commented on internal/app/middleware/middleware.go
> +func Profiler() http.Handler {
А нужна ли нам тогда эта функция, если мы уже импортнули `net/http/pprof`?
Нам достаточно просто на отдельном порту вызвать `http.ListenAndServe` и с импортированным пакетом профилировщика туда автоматически зарегаются эти хэндлеры. Так как рантайм у обоих серверов будет общий, то данные там будут актуальные

2022-06-05 22:49 UTC, Barugoo commented on internal/app/server/server_test.go
> +func BenchmarkHandlerSaveURL(b *testing.B) {
Бенчмарки предназначены для тестирования производительности CPU-bound задач, которые включают: математические вычисления (например хэширование), операции над коллекциями (поиск, вставка, удаление и тд). В нашем случае можно сделать две реализации хранилки урлов - через массив/линкед-лист и через мапку и сравнить их производительность в бенчмарках на разных операциях.

2022-06-05 22:50 UTC, Barugoo commented on internal/app/server/server_test.go
> +}
Круто, что ты добавил в example тесты, но этот функционал больше нужен для юнит-тестов, а не для интеграционных. Здесь по заданию ожидается что-то вроде
https://medium.com/@danielphan/try-things-testing-part-1-a734215b25fa

![изображение](https://user-images.githubusercontent.com/27661724/172073844-96a938e8-3355-4380-8cbf-b2708584534e.png)

2022-06-05 22:50 UTC, Barugoo requested changes
Есть замечания, не вижу файла result.pprof

2022-06-14 11:58 UTC, fd239 commented on internal/app/middleware/middleware.go
> +func Profiler() http.Handler {
Я честно попробовал и мне не удалось импортировать _ net/http/pprof, сделать http.ListenAndServe на другой порт и выполнить тестирование

2022-06-15 14:01 UTC, rktkov approved these changes

2022-06-15 14:01 UTC, rktkov commented on internal/app/middleware/middleware.go
> +func Profiler() http.Handler {
Можно прийти в личку и детали обсудить.

2022-06-19 20:06 UTC, merged